# .github/workflows/ci.yml
name: CI Sanity Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests with coverage and check threshold
        run: |
          set -o pipefail
          npm run test:coverage 2>&1 | tee coverage/coverage_output.txt || echo "::warning ::Test coverage command failed!"
          
          COVERAGE=$(grep -E '^All files' coverage/coverage_output.txt | awk '{print $(NF-1)}' | tr -d '%')
          echo "Total line coverage: $COVERAGE%"
          
          if [ -z "$COVERAGE" ]; then
            echo "::warning ::Could not determine total coverage from output!"
          elif (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "::warning ::Test coverage is below 80%!"
          fi
        shell: bash
